FROM jenkins/inbound-agent
USER root

RUN apt-get update -y && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   buster \
   stable"

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

RUN apt-get update -y && apt-get install -y docker-ce-cli

# need proper user permissions for jenkins user
RUN groupadd docker && usermod -aG docker jenkins 
USER jenkins
